- name: Backup Project Objects - Create local backup structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  loop:
    - "{{ CONTROLLER_BACKUP }}"
  delegate_to: localhost
  vars:
    ansible_connection: ssh
    ansible_user: "{{ ansible_ssh_user }}"

- name: Backup Project Objects - Create remote backup structure
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BACKUPDIR }}"

- name: Check OC login (whoami)
  shell: oc whoami
  register: oc_whoami
  changed_when: false
  failed_when: "OCUSER not in oc_whoami.stdout_lines or oc_whoami.rc != 0"

- name: Backup Project Objects - Generate List of Projects
  shell: oc get projects | awk '{print $1}' | grep -v NAME
  ignore_errors: yes
  changed_when: false
  register: projects

- set_fact:
    projects={{ projects.stdout_lines }}

- name: Backup Project Objects - Openshift Export Objects
  shell: "oc -n {{ item.0 }} get --export {{ item.1 }} -o yaml > {{ BACKUPDIR }}/{{ item.0 }}_{{ item.1 }}.yaml"
  with_nested:
    - "{{ projects }}"
    - "{{ objects }}"

- name: Backup Project Objects - Archive objects
  archive:
    path:
    - "{{ BACKUPDIR }}/*.yaml"
    dest: "{{ BACKUPDIR }}/objects.tgz"

- name: Fetch objects archive
  fetch:
    src: "{{ BACKUPDIR }}/objects.tgz"
    dest: "{{ CONTROLLER_BACKUP }}"
