- name: Backup Node Servers - Create local backup structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  loop:
    - "{{ CONTROLLER_BACKUP }}"
  delegate_to: localhost
  vars:
    ansible_connection: ssh
    ansible_user: "{{ ansible_ssh_user }}"

- name: Backup Node Servers - Create remote backup structure
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BACKUPDIR }}"

- name: Backup Node Servers - Generate Package List from Node Servers
  shell: "rpm -qa | sort"
  register: packages

- name: Backup Node Servers - Save listed packages to packages.txt
  copy:
    content: "{{ packages.stdout_lines }}"
    dest: "{{ BACKUPDIR }}/packages.txt"
    remote_src: true

- name: Backup Node Servers - Copy Origin Files
  archive:
    path:
    - /etc/origin/
    - /etc/sysconfig/atomic-openshift-node
    - /etc/sysconfig/iptables
    - /etc/sysconfig/docker-storage-setup
    - /etc/sysconfig/docker
    - /etc/sysconfig/docker-network
    - /etc/sysconfig/docker-storage
    - /etc/cni/
    - /etc/dnsmasq.d/
    - /etc/dnsmasq.conf
    - /etc/pki/ca-trust/source/anchors/
    - "{{ BACKUPDIR }}/packages.txt"
    dest: "{{ BACKUPDIR }}/node.tgz"

- name: Fetch node archive
  fetch:
    src: "{{ BACKUPDIR }}/node.tgz"
    dest: "{{ CONTROLLER_BACKUP }}"
